### ISSUE TITLE
some remarks about 2d and 3d

### ISSUE THREAD

**Issue by all4one1** [cerrno/mueller-sph#2]
Hi friend, 
first of all, I think it is a very nice project to start understanding SPH
You use 2D formulation, but I think your smoothing kernels are 3D ones. When you differentiate/intergrate in 2D and 3D spherical coordinate system,  there is a difference in comparison to Cartesian coordinate system
Look for example at Laplace operator https://en.wikipedia.org/wiki/Del_in_cylindrical_and_spherical_coordinates

That difference leads to different coefficients in front of a kernel function, e.g.:
Poly6 kernels:  3D (your variant): 315/(64*Pi*H^9), 2D:  4/(Pi*H^8)

You take quite extreme values of some parameters (like gravity G), I may assume it is to due to wrong coefficients for 2D. 
When I changed coefficients from 3d to 2d, I could use much more adequate values.

______
When I tried to run your code, I had to add a line
`glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);`
right after the line: `glutInit(&argc, argv);`

**Comment by all4one1** [comment]
Some discussion here for example
https://math.stackexchange.com/questions/3898821/laplacian-of-viscosity-kernel-function-m%C3%BCller-sph

**Comment by lucas-schuermann** [comment]
Thank you for the note! I have updated the code to use the correct 2D kernels. I found the best reference for the formulation was this [paper](https://www.researchgate.net/publication/221622709_SPH_Based_Shallow_Water_Simulation), where Müller was a collaborator.

Please give it a look and let me know if that matches the work you did. I've also added the `glutInitDisplayMode` flag to improve platform compatibility, though that does not seem to be required for my GLUT distribution/OS.

Cheers!
